---
name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install Tools
      run: sudo apt-get update && sudo apt-get install -y make gcc

    - name: Build Application
      run: go build

    - name: Run Unit Tests
      run: go test
